/* Generated by Together */

#ifndef CMANUVERBOVEVOYRAZVOROT_H
#define CMANUVERBOVEVOYRAZVOROT_H
#include "CManuver.h"
class CManuverBovevoyRazvorot : public CManuver {
};
#endif // CMANUVERBOVEVOYRAZVOROT_H