/* Generated by Together */

#ifndef CPLANERELATION_H
#define CPLANERELATION_H

enum EPlanesAttitude
{
	EPA_ATTACK_DIRECT,
	
	EPA_ATTACK_TAIL,
	EPA_GAIN_SPEED,
	EPA_GAIN_SPEED_FAST,
	EPA_GAIN_HEIGHT,
	EPA_GAIN_HEIGHT_FAST,
	EPA_RETREAT,
	
};

/* * 1) determines the type of interaction of one aircraft relative to another (see table “aircraft behavior.xls”. */
class CPlaneRelation 
{
public:

    /* *
      */
    int GetAttitude(const interface IPlane * pPlane, const interface IPlane *pEnemy);
};
#endif // CPLANERELATION_H