/* Generated by Together */
#include "StdAfx.h"

#include "CPlaneRelation.h"

int CPlaneRelation::GetAttitude( const IPlane *pPlane, const IPlane *pEnemy) 
{ 
	// FOR TEST
	return EPA_ATTACK_DIRECT;
}
